services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: cardnexus
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_network
  text-scan-api:
    build:
      context: text-scan-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
  client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        APP_API: http://localhost:8001
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  mongo_network:
    driver: bridge
